import {
  collection,
  doc,
  getDoc,
  getDocs,
  setDoc,
  query,
  where,
  orderBy,
  limit,
  Timestamp,
  onSnapshot,
} from 'firebase/firestore'

const pad = (n) => String(n).padStart(2, '0')

/**
 * Converts a Date object to a local ISO string (YYYY-MM-DDTHH:mm:ss.sss) without 'Z',
 * matching the format generated by the Flutter POS app (DateTime.now().toIso8601String()).
 */
export const toLocalISOString = (d) => {
  if (!d || !(d instanceof Date) || isNaN(d.getTime())) return ''
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}

/**
 * Calculates start and end Date objects for standard filter ranges.
 * Supports both short ('7d', '30d') and long ('7days', '30days') keys.
 */
export const getDateRangeBounds = (filterRange, customStartStr, customEndStr) => {
  const now = new Date()
  let startDate = null
  let endDate = null

  if (filterRange === 'today') {
    startDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999)
  } else if (filterRange === 'yesterday') {
    const y = new Date(now)
    y.setDate(y.getDate() - 1)
    startDate = new Date(y.getFullYear(), y.getMonth(), y.getDate(), 0, 0, 0, 0)
    endDate = new Date(y.getFullYear(), y.getMonth(), y.getDate(), 23, 59, 59, 999)
  } else if (filterRange === '7d' || filterRange === '7days') {
    startDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6, 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999)
  } else if (filterRange === '30d' || filterRange === '30days') {
    startDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 29, 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999)
  } else if (filterRange === '3m' || filterRange === '3months' || filterRange === '90d') {
    startDate = new Date(now.getFullYear(), now.getMonth() - 3, now.getDate(), 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999)
  } else if (filterRange === '6m' || filterRange === '6months' || filterRange === '180d') {
    startDate = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate(), 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999)
  } else if (filterRange === '12m' || filterRange === '12months' || filterRange === '1y' || filterRange === '365d') {
    startDate = new Date(now.getFullYear() - 1, now.getMonth(), now.getDate(), 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999)
  } else if (filterRange === 'this_month') {
    startDate = new Date(now.getFullYear(), now.getMonth(), 1, 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999)
  } else if (filterRange === 'last_month') {
    startDate = new Date(now.getFullYear(), now.getMonth() - 1, 1, 0, 0, 0, 0)
    endDate = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59, 999)
  } else if (filterRange === 'custom') {
    if (customStartStr) startDate = new Date(customStartStr)
    if (customEndStr) endDate = new Date(customEndStr)
  }

  return { startDate, endDate }
}

/**
 * Normalizes an order's createdAt property into a standard JS Date object.
 * Handles Firestore Timestamps, ISO Strings, local date strings, and millisecond timestamps.
 */
export const normalizeOrderDate = (order) => {
  if (!order) return null
  const val =
    order.createdAt ||
    order.date ||
    order.timestamp ||
    order.updatedAt ||
    order.backedUpAt ||
    order.ticketCreatedAt
  if (!val) return null

  if (typeof val === 'object' && typeof val.toDate === 'function') {
    return val.toDate()
  }
  if (typeof val === 'object' && typeof val.seconds === 'number') {
    return new Date(val.seconds * 1000)
  }
  if (val instanceof Date) {
    return val
  }
  if (typeof val === 'string') {
    // If format is "2026-09-12 10:30:00", replace space with 'T' for standard parsing
    const cleanStr = val.includes(' ') && !val.includes('T') ? val.replace(' ', 'T') : val
    const d = new Date(cleanStr)
    if (!isNaN(d.getTime())) return d
  }
  if (typeof val === 'number') {
    const d = new Date(val)
    if (!isNaN(d.getTime())) return d
  }
  return null
}

/**
 * Strategy 1: Server-Side Query Filters with String & Timestamp Bounds
 * Queries Firestore orders directly, supporting both Flutter POS ISO string dates and Firestore Timestamps.
 */
export const fetchOrdersByDateRange = async (db, targetRestaurantId, startDate, endDate, maxLimit = 5000) => {
  if (!db || !targetRestaurantId) return []

  const ordersMap = new Map()

  const addOrder = (orderData, fallbackId) => {
    if (!orderData || typeof orderData !== 'object') return
    const orderId =
      orderData.id ||
      orderData.orderId ||
      orderData.orderNumber ||
      orderData.invoiceNumber ||
      fallbackId ||
      `order_${Math.random().toString(36).substring(2, 9)}`

    if (!ordersMap.has(orderId)) {
      ordersMap.set(orderId, {
        id: orderId,
        ...orderData,
      })
    }
  }

  const parseDocData = (data, docId) => {
    if (!data) return
    if (Array.isArray(data.orders)) {
      data.orders.forEach((ord, idx) => addOrder(ord, `${docId}_ord_${idx}`))
    } else if (Array.isArray(data.backups)) {
      data.backups.forEach((ord, idx) => addOrder(ord, `${docId}_bk_${idx}`))
    } else if (Array.isArray(data.sales)) {
      data.sales.forEach((ord, idx) => addOrder(ord, `${docId}_sl_${idx}`))
    } else if (Array.isArray(data.items) || data.total !== undefined || data.status || data.createdAt) {
      addOrder(data, docId)
    }
  }

  // 1. Check doc directly at backup/{targetRestaurantId} (handles legacy array doc format)
  try {
    const mainDocRef = doc(db, 'backup', targetRestaurantId)
    const mainDocSnap = await getDoc(mainDocRef)
    if (mainDocSnap.exists()) {
      parseDocData(mainDocSnap.data(), mainDocSnap.id)
    }
  } catch (e) {
    // ignore
  }

  // 2. Candidate subcollections where orders are stored
  const queryCollections = [
    collection(db, 'backup', targetRestaurantId, 'orders'),
    collection(db, 'restaurants', targetRestaurantId, 'orders'),
    collection(db, 'backups', targetRestaurantId, 'orders'),
    collection(db, 'backup', targetRestaurantId, 'sales'),
    collection(db, 'backup', targetRestaurantId, 'records'),
  ]

  const startLocalStr = startDate ? toLocalISOString(startDate) : null
  const endLocalStr = endDate ? toLocalISOString(endDate) : null
  const startTs = startDate ? Timestamp.fromDate(startDate) : null
  const endTs = endDate ? Timestamp.fromDate(endDate) : null

  for (const colRef of queryCollections) {
    try {
      let fetched = false

      // A. Try query with Flutter POS local ISO string bounds
      if (startLocalStr && endLocalStr) {
        try {
          const qStr = query(
            colRef,
            where('createdAt', '>=', startLocalStr),
            where('createdAt', '<=', endLocalStr),
            limit(maxLimit)
          )
          const snapStr = await getDocs(qStr)
          if (!snapStr.empty) {
            snapStr.forEach((docSnap) => parseDocData(docSnap.data(), docSnap.id))
            fetched = true
          }
        } catch (e) {
          // Index might not exist or field type differs
        }
      }

      // B. Try query with Firestore Timestamp bounds
      if (!fetched && startTs && endTs) {
        try {
          const qTs = query(
            colRef,
            where('createdAt', '>=', startTs),
            where('createdAt', '<=', endTs),
            limit(maxLimit)
          )
          const snapTs = await getDocs(qTs)
          if (!snapTs.empty) {
            snapTs.forEach((docSnap) => parseDocData(docSnap.data(), docSnap.id))
            fetched = true
          }
        } catch (e) {
          // Field is not a timestamp
        }
      }

      // C. General fallback query with safety limit
      if (!fetched) {
        try {
          const snapFallback = await getDocs(query(colRef, limit(maxLimit)))
          if (!snapFallback.empty) {
            snapFallback.forEach((docSnap) => parseDocData(docSnap.data(), docSnap.id))
          }
        } catch (e) {
          // Collection doesn't exist
        }
      }
    } catch (e) {
      // Continue to next collection
    }
  }

  // Filter in memory to guarantee exact local time boundaries
  let result = Array.from(ordersMap.values())
  if (startDate || endDate) {
    result = result.filter((order) => {
      const d = normalizeOrderDate(order)
      if (!d) return true
      if (startDate && d < startDate) return false
      if (endDate && d > endDate) return false
      return true
    })
  }

  return result
}

/**
 * Strategy 3: Restrict Real-time Listener to Active Shift (Today Only)
 * Attaches an onSnapshot listener scoped strictly to createdAt >= startOfToday.
 */
export const subscribeToTodayOrders = (db, targetRestaurantId, onUpdate, onError) => {
  if (!db || !targetRestaurantId) return () => {}

  const now = new Date()
  const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0)
  const startLocalStr = toLocalISOString(startOfToday)
  const liveCol = collection(db, 'backup', targetRestaurantId, 'orders')

  let q
  try {
    q = query(liveCol, where('createdAt', '>=', startLocalStr))
  } catch {
    try {
      q = query(liveCol, limit(300))
    } catch {
      q = liveCol
    }
  }

  return onSnapshot(
    q,
    (snapshot) => {
      if (snapshot.empty) {
        onUpdate([])
        return
      }

      const orders = []
      snapshot.forEach((docSnap) => {
        const data = docSnap.data()
        if (Array.isArray(data.orders)) {
          data.orders.forEach((ord, idx) => {
            orders.push({ id: ord.id || `${docSnap.id}_${idx}`, ...ord })
          })
        } else {
          orders.push({ id: docSnap.id, ...data })
        }
      })

      // Ensure exact local day matching
      const todayOnly = orders.filter((o) => {
        const d = normalizeOrderDate(o)
        if (!d) return true
        return d >= startOfToday
      })
      onUpdate(todayOnly)
    },
    (err) => {
      if (typeof onError === 'function') onError(err)
      else console.warn('Realtime orders listener notice:', err)
    }
  )
}

/**
 * Strategy 2: Pre-Aggregated Daily Summary Rollups
 * Saves or updates a daily summary document at restaurants/{restaurantId}/daily_summaries/{YYYY-MM-DD}
 */
export const saveDailySummary = async (db, targetRestaurantId, dateKey, summaryData) => {
  if (!db || !targetRestaurantId || !dateKey || !summaryData) return false
  try {
    const summaryRef = doc(db, 'restaurants', targetRestaurantId, 'daily_summaries', dateKey)
    await setDoc(
      summaryRef,
      {
        date: dateKey,
        ...summaryData,
        updatedAt: Timestamp.now(),
      },
      { merge: true }
    )
    return true
  } catch (err) {
    console.warn('Failed to save daily summary rollup:', err)
    return false
  }
}

/**
 * Strategy 2: Fetch Pre-Aggregated Daily Summaries for Range
 */
export const fetchDailySummariesRange = async (db, targetRestaurantId, startDateStr, endDateStr) => {
  if (!db || !targetRestaurantId) return []
  try {
    const summariesCol = collection(db, 'restaurants', targetRestaurantId, 'daily_summaries')
    let q = query(summariesCol, orderBy('date', 'desc'), limit(365))
    if (startDateStr && endDateStr) {
      q = query(
        summariesCol,
        where('date', '>=', startDateStr),
        where('date', '<=', endDateStr),
        orderBy('date', 'asc')
      )
    }
    const snap = await getDocs(q)
    if (snap.empty) return []
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }))
  } catch (err) {
    console.warn('Daily summaries range query note:', err)
    return []
  }
}
